### ISSUE TITLE
Bug: Download Button doesn't have an indicator

### ISSUE THREAD

**Issue by PixelDuals** [Kropatz/boorusphere#4]
### Type

UI-related issues

### Bug description

Previously the Download button had an indicator when something was downloaded, the button turned blue, but for some reason when i click the download button now it don't show an indicator that the download was completed.

### Steps to reproduce

Step 1. Open an image/video on any booru
Step 2. Click the download button

### Android version

Android 14

### App version

1.4.7

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Kropatz** [comment]
Should be fixed with 1.4.8
